language: node_js

node_js:
  - node

branches:
  only:
    - master
    - develop
    - /^feature-.*$/
    - /^release-.*$/
    - /^fix-.*$/

jobs:
  include:
    - stage: test
      script: npm run lint
      script: npm run coveralls
      script: npm run build
    - stage: deploy
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release