language: node_js

node_js:
  - node

script:
  - npm run prepublish
  - npm run coveralls

branches:
  only:
    - master
    - develop
    - /^feature-.*$/
    - /^release-.*$/
    - /^fix-.*$/

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master