name: Test, Build and Report Coverage

on:
  push:
    branches: [ master, deploy, feature/*, fix/*, release/* ]
  pull_request:
    branches: [ master, deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint source files
        run: npm run lint
      - name: Run tests and produce coverage
        run: npm run test:coverage
      - name: Build source files
        run: npm run build
      - uses: actions/upload-artifact@v2
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        path: |
          dist/**
          lib/**
          es/**
          types/**
      - name: Coveralls report
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info